apiVersion: v1
kind: Service
metadata:
  name: go-vmw-license-status
spec:
  type: ClusterIP
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: go-vmw-license-status
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-vmw-license-status
spec:
  replicas: 5
  selector:
    matchLabels:
      app: go-vmw-license-status
      deletable: yes
  template:
    metadata:
      labels:
        app: go-vmw-license-status
        deletable: yes
    spec:
      containers:
      - name: go-vmw-license-status
        image: 172.100.100.134/vvv/go-vmw-license-status:latest
        ports:
        - containerPort: 8081
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 3
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
